import Head from 'next/head'
import {Quiz_Component} from '../../Quiz_Comp/LoadQuiz';

export default function Home() {
  
    return (
      <>
            <Head>
              <title> Home </title>
              <meta name="description" content="Generated by create next app" />
            </Head>
            <Quiz_Component/> 
      </>
    )
  }

  