//import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router';

/*export const getStaticProps=async()=>{
  const res=await axios('')
  const data=res.json()
  return{
    props:{data}
  }

}*/


export default function Home({data}) {

  const router=useRouter()
  const {query:{name, category}}=router

    return (
      <div>
        <Head>
          <title> Home </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  <div>
    Quiz Page
  </div>
        {name}-{category}
      </div>
    )
  }