import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router';


export default function Home() {
  //console.log(data)

  const router=useRouter()
  const {query:{names, category}}=router
  
    return (
      <div>
        <Head>
          <title> Home </title>
          <meta name="description" content="Generated by create next app" />
        </Head>
            <div>
              Quiz Page
            </div>
        {names}-{category}
      </div>
    )
  }

  /*export const getStaticProps=async({category})=>{
    const {data} = await axios.get(`https://opentdb.com/api.php?amount=10&category=${category}&type=multiple`)
    console.log(data)
    return{
      props:{data}
    }
  
  }*/