import Head from 'next/head'
import { useState } from 'react';
import { DropMenu } from '../Home_Page/Drop_menu';

export default function Home() {

  const [name, setName]=useState ('')
  const [category, setCategory]=useState('')

  return (
    <div>
            <Head>
              <title> My Quiz App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

      
            <div>
              <DropMenu 
                  name={name} 
                  setName={setName} 
                  category={category} 
                  setCategory={setCategory}
                />
            </div>
      
    </div>
  )
}
